object Versions {
  lazy val akkaHttpJson4sVersion      = "1.38.2"
  lazy val akkaHttpVersion            = "10.2.6"
  lazy val akkaVersion                = "2.6.17"
  lazy val apacheCommonsTextVersion   = "1.9"
  lazy val awsSdkVersion              = "2.17.159"
  lazy val azureStorageBlobVersion    = "12.15.0"
  lazy val catsVersion                = "2.7.0"
  lazy val commonsFileUploadVersion   = "1.4"
  lazy val courierVersion             = "3.1.0"
  lazy val httpJson4sVersion          = "1.38.2"
  lazy val jacksonVersion             = "2.11.4"
  lazy val json4sVersion              = "4.0.3"
  lazy val jsoupVersion               = "1.14.3"
  lazy val lightbendLoggingVersion    = "3.9.4"
  lazy val logbackVersion             = "1.2.11"
  lazy val mockJavaMailVersion        = "1.9"
  lazy val nimbusVersion              = "9.21"
  lazy val openhtmltopdfVersion       = "1.0.10"
  lazy val pdfBoxVersion              = "2.0.25"
  lazy val pdfCompareVersion          = "1.1.61"
  lazy val s3Persistence              = "1.1.74"
  lazy val scalatestVersion           = "3.2.11"
  lazy val swaggerValidatorVersion    = "2.27.0"
  lazy val testContainersScalaVersion = "0.40.4"
  lazy val typesafeConfigVersion      = "1.4.2"
  lazy val vaultDriverVersion         = "5.1.0"
}
