object Versions {
  lazy val akkaVersion              = "2.6.17"
  lazy val akkaHttpVersion          = "10.2.6"
  lazy val awsSdkVersion            = "2.17.72"
  lazy val azureStorageBlobVersion  = "12.14.1"
  lazy val s3Persistence            = "1.1.74"
  lazy val httpJson4sVersion        = "1.38.2"
  lazy val json4sVersion            = "4.0.3"
  lazy val jacksonVersion           = "2.11.4"
  lazy val commonsFileUploadVersion = "1.4"
  lazy val logbackVersion           = "1.2.6"
  lazy val scalatestVersion         = "3.2.10"
  lazy val mockitoVersion           = "3.9.0"
  lazy val akkaHttpJson4sVersion    = "1.38.2"
  lazy val typesafeConfigVersion    = "1.4.1"
  lazy val courierVersion           = "3.0.1"
}
